# Generated by Django 3.2.4 on 2021-06-02 14:09

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=localflavor.us.models.USPostalCodeField(default='NC', max_length=2),
            preserve_default=False,
        ),
    ]
