# Generated by Django 3.2.4 on 2021-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_auto_20210602_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240, null=True)),
                ('zones', models.ManyToManyField(related_name='plants', to='garden.GrowingZone')),
            ],
        ),
    ]
