# Generated by Django 3.2.4 on 2021-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_growingzone_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='common_name',
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
