# Generated by Django 3.2.4 on 2021-06-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_auto_20210602_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('PM', 'Piedmont'), ('MT', 'Mountains'), ('CP', 'Coastal Plain')], default='PM', max_length=100),
            preserve_default=False,
        ),
    ]
